### ISSUE TITLE
Request: Custom server creation

### ISSUE THREAD

**Issue by petericebear** [mpociot/blacksmith#1]
Hi Marcel,

Do you think this can be done? And do you have this in your feature list to build?
Will look into aswell, but maybe you are looking into it at this moment.
Greetings,
Peter

**Comment by mpociot** [comment]
Hi Peter,

this can certainly be done! I'm currently not looking into this feature in particular because I'm looking into the APIs to create keys / databases / deployments / etc.
So APIs which require a site to be configured in the first place.

**Comment by petericebear** [comment]
I see what it does.. Will try to do it tonight or tomorrow

**Comment by petericebear** [comment]
How would you like the creation of all kind of servers? Would you like some helpers for it for creating a provider server, or custom server with some default configuration?

For instance:
createCustomLoadBalancer()
createCustomServer
createServer(Provider, Backups)

Do you want some extra help for the Circle management? For adding/removing server from a Circle?

**Comment by mpociot** [comment]
I personally think the current `addServer` method is sufficient.

Could you just send a PR to the README describing all server configuration fields possible?

**Comment by mpociot** [comment]
Maybe we should add a wiki to this repository where we describe the different API calls - the README could become quite crowded soon :)

**Comment by petericebear** [comment]
I think that will be a great Idea.. More features are coming quick :)
Circles almost complete..
