### ISSUE TITLE
Ability to update the servers IP

### ISSUE THREAD

**Issue by djekl** [mpociot/blacksmith#2]
The ability to update a servers IP programmatically would mean that Laravel Forge can eventually work like a dynamic host. My friends and I have a small test server running from a non static IP. Its IP updates once every few months, so its not a hassle to update, but the ability to update this automatically would be perfect!

If I can get some time, I will have a look at this myself, and hopefully create a PR. However if @mpociot can do it faster, I wouldn't complain...

**Comment by mpociot** [comment]
Where can you update the servers IP address in the forge backend?
Is this done through the server metadata?

**Comment by djekl** [comment]
Its under the `meta` tab as `metaForm.ipAddress`
